# Generated by Django 3.0.5 on 2022-05-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20220506_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
